// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4DQvGfXtf2VRLJZpQL0UKM7-EkRpTsHY',
    appId: '1:121178413368:web:e20fb64ea85681e176c9cd',
    messagingSenderId: '121178413368',
    projectId: 'learn-flutter-3e7e8',
    authDomain: 'learn-flutter-3e7e8.firebaseapp.com',
    storageBucket: 'learn-flutter-3e7e8.appspot.com',
    measurementId: 'G-J6LSSZ4LWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoUFROonHmOoRTDAoioec8x3_rBmzWLSU',
    appId: '1:121178413368:android:f632c99422462c9576c9cd',
    messagingSenderId: '121178413368',
    projectId: 'learn-flutter-3e7e8',
    storageBucket: 'learn-flutter-3e7e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7AItiW2dhVflXIq_K9sSOOLWKJNnmIPo',
    appId: '1:121178413368:ios:678e8d1627b1c3e776c9cd',
    messagingSenderId: '121178413368',
    projectId: 'learn-flutter-3e7e8',
    storageBucket: 'learn-flutter-3e7e8.appspot.com',
    iosBundleId: 'com.example.praktikum6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7AItiW2dhVflXIq_K9sSOOLWKJNnmIPo',
    appId: '1:121178413368:ios:678e8d1627b1c3e776c9cd',
    messagingSenderId: '121178413368',
    projectId: 'learn-flutter-3e7e8',
    storageBucket: 'learn-flutter-3e7e8.appspot.com',
    iosBundleId: 'com.example.praktikum6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4DQvGfXtf2VRLJZpQL0UKM7-EkRpTsHY',
    appId: '1:121178413368:web:d50839b604697d5076c9cd',
    messagingSenderId: '121178413368',
    projectId: 'learn-flutter-3e7e8',
    authDomain: 'learn-flutter-3e7e8.firebaseapp.com',
    storageBucket: 'learn-flutter-3e7e8.appspot.com',
    measurementId: 'G-VBFK53SH6J',
  );
}